Colegio/Controllers/XMLFormatController.cs
using Colegio.Models;
using Colegio.Models.XMLFormat;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Colegio.Controllers
{
    public class XMLFormatController : Controller
    {
       public async Task<dynamic> XMLFormat()
        {
            try
            {
                List<XMLFormat> xmlList = new List<XMLFormat>();
                HttpClient client = new HttpClient();
                string apiCrud = System.Configuration.ConfigurationManager.AppSettings["UrlAPI"] + "api/XML";
                HttpResponseMessage httpResponse = await client.GetAsync(apiCrud);
                if(httpResponse.IsSuccessStatusCode)
                {
                    string response = await httpResponse.Content.ReadAsStringAsync();
                    List<XMLFormat> format = JsonConvert.DeserializeObject<List<XMLFormat>>(response);
                    

                    return View(format);
                }
                return View();
            }
            catch(Exception ex)
            {
                return View("Error", ex.Message);
            }
        }
    }
}

Colegio/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Colegio .Net</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Colegio .Net", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Alternar navegación" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    @*<li>@Html.ActionLink("Inicio", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>*@
                    <li class="nav-link">|</li>
                    <li>@Html.ActionLink("Registrar alumno", "RegistroAlumno", "Register", new { area = "" }, new { @class = "nav-link" })
                    @Html.ActionLink("Lista de alumnos", "ListaAlumnos", "Lists", new { area = "" }, new { @class = "nav-link" })</li>
                    <li class="nav-link">|</li>
                    <li>@Html.ActionLink("Registrar profesor", "RegistroProfesor", "Register", new { area = "" }, new { @class = "nav-link" })
                    @Html.ActionLink("Lista de profesores", "ListaProfesores", "Lists", new { area = "" }, new { @class = "nav-link" })</li>
                    <li class="nav-link">|</li>
                    <li>@Html.ActionLink("Registrar asignaturas", "RegistroAsignatura", "Register", new { area = "" }, new { @class = "nav-link" })
                    @Html.ActionLink("Lista de asignaturas", "ListaAsignatura", "Lists", new { area = "" }, new { @class = "nav-link" })</li>
                    <li class="nav-link">|</li>
                    <li>@Html.ActionLink("Reporte de compras", "XMLFormat", "XMLFormat", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Colegio .NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>