Colegio/Controllers/CrudController.cs
using Antlr.Runtime.Misc;
using Colegio.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Net.Http;
using System.Security.Policy;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Colegio.Controllers
{
    public class CrudController : Controller
    {
        //public ActionResult Eliminar(string id, string name)
        //{
        //    return RedirectToAction("ListaAlumnos", "Lists");
        //}

        public async Task<dynamic> Editar(string id, string asg, string name)
        {
            var result = await new ListsController().Buscar(id, asg, name, "Editar");

            string json = JsonConvert.SerializeObject(result);

            switch (name)
            {
                case "alumno":
                    return RedirectToAction("RegistroAlumno", "Register", new { alumno = json });
                case "profesor":
                    return RedirectToAction("RegistroProfesor", "Register", new { profesor = json });
                case "asignatura":
                    return RedirectToAction("RegistroAsignatura", "Register", new { asignatura = json });
                default:
                    return RedirectToAction("Index", "Home");
            }
        }

        public async Task<dynamic> ActualizarAlumno(string id, string nombre, string apellido, string edad, string direccion, string telefono, string asignatura, string asignaturaOld, string calificacion = null)
        {
            try
            {
                Alumno alumno = new Alumno();
 
                alumno.Nombre = nombre;
                alumno.Apellido = apellido;
                alumno.Edad = edad;
                alumno.Direccion = direccion;
                alumno.Telefono = telefono;
                alumno.Asignatura = asignatura;
                alumno.Calificacion = calificacion == null ? "" : calificacion;

                var jsonAlumno = new StringContent(JsonConvert.SerializeObject(alumno), Encoding.UTF8, "application/json");
               
                HttpClient client = new HttpClient();
                string apiCrud = System.Configuration.ConfigurationManager.AppSettings["UrlAPI"] + "api/actualizar/alumno" + "?id=" + id + "&asg=" + asignatura + "&asgOld=" + asignaturaOld;
                HttpResponseMessage httpResponse = await client.PostAsync(apiCrud, jsonAlumno);
                if (httpResponse.IsSuccessStatusCode)
                {
                    TempData["AlertMessage"] = "¡Datos guardados correctamente!";
                    TempData["AlertType"] = "success";
                    return RedirectToAction("ListaAlumnos", "Lists");
                }
                else
                {
                    TempData["AlertMessage"] = "¡Datos no guardados!";
                    TempData["AlertType"] = "success";
                    return RedirectToAction("ListaAlumnos", "Lists");
                }

            }
            catch(Exception ex)
            {
                return View("Error", ex.Message);
            }
        }

        public async Task<dynamic> ActualizarProfesor(string id, string nombre, string apellido, string edad, string direccion, string telefono, string asignatura)
        {
            try
            {
                Profesor alumno = new Profesor();

                alumno.Nombre = nombre;
                alumno.Apellido = apellido;
                alumno.Edad = edad;
                alumno.Direccion = direccion;
                alumno.Telefono = telefono;
                alumno.Asignatura = asignatura;


                var jsonProfesor = new StringContent(JsonConvert.SerializeObject(alumno), Encoding.UTF8, "application/json");

                HttpClient client = new HttpClient();
                string apiCrud = System.Configuration.ConfigurationManager.AppSettings["UrlAPI"] + "api/actualizar/profesor" + "?id=" + id;
                HttpResponseMessage httpResponse = await client.PostAsync(apiCrud, jsonProfesor);
                if (httpResponse.IsSuccessStatusCode)
                {
                    TempData["AlertMessage"] = "¡Datos guardados correctamente!";
                    TempData["AlertType"] = "success";
                    return RedirectToAction("ListaProfesores", "Lists");
                }
                else
                {
                    TempData["AlertMessage"] = "¡Datos no guardados!";
                    TempData["AlertType"] = "success";
                    return RedirectToAction("ListaProfesores", "Lists");
                }

            }
            catch (Exception ex)
            {
                return View("Error", ex.Message);
            }
        }

        public async Task<dynamic> ActualizarAsignatura(string id, string nombre)
        {
            try
            {
                Asignatura alumno = new Asignatura();

                alumno.Nombre = nombre;

                var jsonAsignatura = new StringContent(JsonConvert.SerializeObject(alumno), Encoding.UTF8, "application/json");

                HttpClient client = new HttpClient();
                string apiCrud = System.Configuration.ConfigurationManager.AppSettings["UrlAPI"] + "api/actualizar/asignatura" + "?id=" + id;
                HttpResponseMessage httpResponse = await client.PostAsync(apiCrud, jsonAsignatura);
                if (httpResponse.IsSuccessStatusCode)
                {
                    TempData["AlertMessage"] = "¡Datos guardados correctamente!";
                    TempData["AlertType"] = "success";
                    return RedirectToAction("ListaAsignatura", "Lists");
                }
                else
                {
                    TempData["AlertMessage"] = "¡Datos no guardados!";
                    TempData["AlertType"] = "success";
                    return RedirectToAction("ListaAsignatura", "Lists");
                }

            }
            catch (Exception ex)
            {
                return View("Error", ex.Message);
            }
        }

        public async Task<dynamic> Eliminar(string id, string asg, string name)
        {
            try
            {
                HttpClient client = new HttpClient();
                string url = System.Configuration.ConfigurationManager.AppSettings["UrlAPI"] + "api/eliminar" + "?id=" + id + "&asg=" + asg + "&name=" + name;
                HttpResponseMessage httpResponse = await client.GetAsync(url);
                if(httpResponse.IsSuccessStatusCode)
                {
                    TempData["AlertMessage"] = "¡Datos guardados correctamente!";
                    TempData["AlertType"] = "success";   
                }
                else
                {
                    TempData["AlertMessage"] = "¡Datos no guardados!";
                    TempData["AlertType"] = "error";
                }
                switch (name)
                {
                    case "alumno":
                        return RedirectToAction("ListaAlumnos", "Lists");

                    case "profesor":
                        return RedirectToAction("ListaProfesores", "Lists");

                    case "asignatura":
                        return RedirectToAction("ListaAsignatura", "Lists");

                    default: return RedirectToAction("Index", "Home");
                }
                

            }
            catch(Exception ex)
            {
                return View("Error", ex.Message);
            }
        }

    }
}

Colegio/Controllers/ListsController.cs
using Colegio.Models;
using Microsoft.Ajax.Utilities;
using Newtonsoft.Json;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Globalization;
using System.Linq;
using System.Net.Http;
using System.Reflection.Emit;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Xml.Linq;

namespace Colegio.Controllers
{
    public class ListsController : Controller
    {
        #region Vistas de las listas
        /// <summary>
        /// Retirno de datos a la vista
        /// </summary>
        /// <returns></returns>
        public async Task<ActionResult> ListaAlumnos()
        {
            try
            {
                List<Alumno> data = (List<Alumno>)Session["Lista"];

                if (data != null)
                {
                    Session.Clear();
                    return View(data);
                }else
                {
                    var dataAlumno = await ObtenerAlumnoAsync();
                    return View(dataAlumno);
                }               
                
                
            }
            catch (Exception ex)
            {
                return View("Error", ex.Message);
            }
        }

        public async Task<dynamic> ListaProfesores()
        {
            try
            {
                List<Profesor> data = (List<Profesor>)Session["Lista"];

                if (data != null)
                {
                    Session.Clear();
                    return View(data);
                }
                else
                {
                    var dataProfesor = await ObtenerProfesorAsync();
                    return View(dataProfesor);
                }
            }
            catch (Exception ex)
            {
                return View("Error", ex.Message);
            }
        }

        public async Task<ActionResult> ListaAsignatura()
        {
            try
            {
                List<Asignatura> data = (List<Asignatura>)Session["Lista"];

                if (data != null)
                {
                    Session.Clear();
                    return View(data);
                }
                else
                {
                    var dataAsignatura = await ObtenerAsignaturaAsync();
                    return View(dataAsignatura);
                }
            }
            catch (Exception ex)
            {
                return View("Error", ex.Message);
            }
        }

        #endregion

        /// <summary>
        /// Obtener la data de las diretentes tablas
        /// </summary>
        /// <returns></returns>
        /// 
        #region Operadores de las listas

        public async Task<dynamic> ObtenerAlumnoAsync()
        {
            try
            {
                HttpClient client = new HttpClient();

                string apiCrud = System.Configuration.ConfigurationManager.AppSettings["UrlAPI"] + "api/listar" + "?name=alumno";
                HttpResponseMessage ResponseAlumno = await client.GetAsync(apiCrud);
                if (ResponseAlumno.IsSuccessStatusCode)
                {
                    string response = await ResponseAlumno.Content.ReadAsStringAsync();
                    List<Alumno> data = JsonConvert.DeserializeObject<List<Alumno>>(response);

                    return data;
                }
                else
                {
                    return View("Error");
                }
            }
            catch (Exception ex)
            {
                return null;
            }
        }

        public async Task<dynamic> ObtenerProfesorAsync()
        {
            try
            {
                HttpClient client = new HttpClient();

                string apiCrud = System.Configuration.ConfigurationManager.AppSettings["UrlAPI"] + "api/listar" + "?name=profesor";
                HttpResponseMessage ResponseAsignatura = await client.GetAsync(apiCrud);
                if (ResponseAsignatura.IsSuccessStatusCode)
                {
                    string response = await ResponseAsignatura.Content.ReadAsStringAsync();
                    List<Profesor> data = JsonConvert.DeserializeObject<List<Profesor>>(response);
                    
                    return data;
                }
                else
                {
                    return View("Error");
                }
            }
            catch (Exception ex)
            {
                return View("Error", ex.Message);
            }
        }

        public async Task<dynamic> ObtenerAsignaturaAsync()
        {
            try
            {
                HttpClient client = new HttpClient();

                string apiCrud = System.Configuration.ConfigurationManager.AppSettings["UrlAPI"] + "api/listar" + "?name=asignatura";
                HttpResponseMessage ResponseAsignatura = await client.GetAsync(apiCrud);
                if (ResponseAsignatura.IsSuccessStatusCode)
                {
                    string response = await ResponseAsignatura.Content.ReadAsStringAsync();
                   List<Asignatura> data = JsonConvert.DeserializeObject<List<Asignatura>>(response);
                    
                    return data;
                }
                else
                {
                    return View("Error");
                }
            }
            catch (Exception ex)
            {
                return null;
            }
        }

        public async Task<dynamic> Buscar(string buscar, string asg, string name, string accion=null)
        {
            try
            {
                HttpClient client = new HttpClient();
                string url = System.Configuration.ConfigurationManager.AppSettings["UrlAPI"] + "api/buscar" + "?Id=" + buscar + "&asg=" + asg + "&name=" + name;

                HttpResponseMessage httpResponse = await client.GetAsync(url);
                if (httpResponse.IsSuccessStatusCode)
                {
                    string response = await httpResponse.Content.ReadAsStringAsync();
                    switch (name)
                    {
                        case "alumno":
                            List<Alumno> dataAlm = JsonConvert.DeserializeObject<List<Alumno>>(response);
                            if (accion != null)
                            {
                                return dataAlm;
                            }
                            else
                            {
                                Session["Lista"] = dataAlm;
                                return RedirectToAction("ListaAlumnos", "Lists");
                            }
                        case "profesor":
                            List<Profesor> dataPrf = JsonConvert.DeserializeObject<List<Profesor>>(response);
                            if (accion != null)
                            {
                                return dataPrf;
                            }
                            else
                            {
                                Session["Lista"] = dataPrf;
                                return RedirectToAction("ListaProfesores", "Lists");
                            }
                        case "asignatura":
                            List<Asignatura> dataAsg = JsonConvert.DeserializeObject<List<Asignatura>>(response);
                            Session["Lista"] = dataAsg;
                            return RedirectToAction("ListaAsignatura", "Lists");
                        default: return RedirectToAction("ListaAlumnos", "Lists");
                    }
                }
                else
                {
                    return View("Error");
                }
            }
            catch (Exception ex)
            {
                return View("Error", ex.Message);
            }
        }

        #endregion
    }
}

Colegio/Views/Lists/ListaAlumnos.cshtml
@{
    ViewBag.Title = "Lista de Alumnos";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <br />
    <div>
        <div>
            <form action="/Lists/Buscar" method="post">
                <table class="table">
                    <thead>
                        <tr>
                            <td>
                                <center><label>Buscar</label></center>
                            </td>
                            <td>
                                <input type="number" id="buscar" name="buscar" value="Alumno" placeholder="Buscar Identificacion" required />
                                <input type="hidden" id="name" name="name" value="alumno" readonly />
                            </td>
                        </tr>
                        <tr>
                            <td></td>
                            <td colspan="2"><button type="submit" class="btn btn-primary" style="width:30%; ">Buscar</button></td>
                        </tr>
                    </thead>
                </table>
            </form>
        </div>
        <br />
        <table class="table table-striped">
            <thead class="bg-dark">
                <tr class="text-white">
                    <td>Año <br />academico </td>
                    <td>Identificacion<br />Alumno </td>
                    <td>Nombre<br />Alumno </td>
                    <td>Edad</td>
                    <td>Direccion</td>
                    <td>Telefono</td>
                    <td>Asignatura</td>
                    <td>Calificacion</td>
                    <td colspan="2"><center>Acciones</center></td>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>2023</td>
                        <td>@item.Id</td>
                        <td>@item.Nombre @item.Apellido</td>
                        <td>@item.Edad</td>
                        <td>@item.Direccion</td>
                        <td>@item.Telefono</td>
                        <td>@item.Asignatura</td>
                        <td>@item.Calificacion</td>
                        <td>
                            <a href="@Url.Action("Editar", "Crud", new { id = item.Id, asg = item.Asignatura ,name = "alumno"})">
                                <img src="~/Content/Images/pencil-fill.svg" class="card-img-bottom" alt="Imagen" />
                            </a>
                        </td>
                        <td>
                            <a href="@Url.Action("Eliminar", "Crud", new {id = item.Id, asg = item.Asignatura, name = "alumno"}) ">
                                <img src="~/Content/Images/trash2-fill.svg" class="card-img-bottom" alt="Imagen" />
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</main>

Colegio/Views/Lists/ListaAsignatura.cshtml
@{
    ViewBag.Title = "Lista de asignatura";
}

<h2>Lista de asignaturas</h2>

<br />
<div>
    <form action="/Lists/Buscar" method="post">
        <table class="table">
            <thead>
                <tr>
                    <td>
                        <center><label>Buscar</label></center>
                    </td>
                    <td>
                        <input type="number" id="buscar" name="buscar" value="Alumno" placeholder="Buscar Codigo" required />
                        <input type="hidden" id="name" name="name" value="asignatura" readonly />
                    </td>
                </tr>
                <tr>
                    <td></td>
                    <td colspan="2"><button type="submit" class="btn btn-primary" style="width:30%; ">Buscar</button></td>
                </tr>
            </thead>
        </table>
    </form>
</div>
<br />
<div>
    <table class="table table-striped-columns">
        <thead>
            <tr>
                <td>Codigo<br />asignatura</td>
                <td>Nombre<br />asignatura</td>
                <td colspan="2"><center>Acciones</center></td>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Id</td>
                    <td>@item.Nombre</td>
                    <td>
                        <a href="@Url.Action("Editar", "Crud", new { id = item.Id, asg = item.Nombre ,name = "Asignatura"})">
                            <center><img src="~/Content/Images/pencil-fill.svg" class="carousel-control-prev-icon" alt="Imagen" /></center>
                        </a>
                    </td>
                    <td>
                        <a href="@Url.Action("Eliminar", "Crud", new {id = item.Id, name = "asignatura"}) ">
                            <center><img src="~/Content/Images/trash2-fill.svg" class="carousel-control-prev-icon" alt="Imagen" /></center>
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

Colegio/Views/Lists/ListaProfesores.cshtml
@{
    ViewBag.Title = "Lista de profesores";
}
<main>
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <br />
    <div>
        <form action="/Lists/Buscar" method="post">
            <table class="table">
                <thead>
                    <tr>
                        <td>
                            <center><label>Buscar</label></center>
                        </td>
                        <td>
                            <input type="number" id="buscar" name="buscar" value="Alumno" placeholder="Buscar Identificacion" required />
                            <input type="hidden" id="name" name="name" value="profesor" readonly />
                        </td>
                    </tr>
                    <tr>
                        <td></td>
                        <td colspan="2"><button type="submit" class="btn btn-primary" style="width:30%; ">Buscar</button></td>
                    </tr>
                </thead>
            </table>
        </form>
    </div>
    <br />
    <div>
        <table class="table table-striped-columns">
            <thead>
                <tr>
                    <td>Año <br />academico </td>
                    <td>Identificacion<br />Alumno </td>
                    <td>Nombre<br />Alumno </td>
                    <td>Edad</td>
                    <td>Direccion</td>
                    <td>Telefono</td>
                    <td>Materia</td>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>2023</td>
                        <td>@item.Id</td>
                        <td>@item.Nombre @item.Apellido</td>
                        <td>@item.Edad</td>
                        <td>@item.Direccion</td>
                        <td>@item.Telefono</td>
                        <td>@item.Asignatura</td>
                        <td>
                            <a href="@Url.Action("Editar", "Crud", new { id = item.Id ,name = "profesor"})">
                                <img src="~/Content/Images/pencil-fill.svg" class="card-img-bottom" alt="Imagen" />
                            </a>
                        </td>
                        <td>
                            <a href="@Url.Action("Eliminar", "Crud", new {id = item.Id, name = "profesor"}) ">
                                <img src="~/Content/Images/trash2-fill.svg" class="card-img-bottom" alt="Imagen" />
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</main>